/*! Video.js v4.6.4 Copyright 2014 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */ 
(function() {var b=void 0,f=!0,k=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function r(a){return function(){return a}}var s;document.createElement("video");document.createElement("audio");document.createElement("track");function t(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(t.Aa[a])return t.Aa[a];a=t.v(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new t.Player(a,c,d)}
var videojs=t;window.qe=window.re=t;t.Tb="4.6";t.Qc="https:"==document.location.protocol?"https://":"http://";t.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,playbackRates:[],children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{},errorDisplay:{}},notSupportedMessage:"No compatible source was found for this video."};"GENERATED_CDN_VSN"!==t.Tb&&(videojs.options.flash.swf=t.Qc+"vjs.zencdn.net/"+t.Tb+"/video-js.swf");
t.Aa={};"function"===typeof define&&define.amd?define([],function(){return videojs}):"object"===typeof exports&&"object"===typeof module&&(module.exports=videojs);t.qa=t.CoreObject=m();t.qa.extend=function(a){var c,d;a=a||{};c=a.init||a.j||this.prototype.init||this.prototype.j||m();d=function(){c.apply(this,arguments)};d.prototype=t.i.create(this.prototype);d.prototype.constructor=d;d.extend=t.qa.extend;d.create=t.qa.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};
t.qa.create=function(){var a=t.i.create(this.prototype);this.apply(a,arguments);return a};t.d=function(a,c,d){if(t.i.isArray(c))return u(t.d,a,c,d);var e=t.getData(a);e.D||(e.D={});e.D[c]||(e.D[c]=[]);d.w||(d.w=t.w++);e.D[c].push(d);e.X||(e.disabled=l,e.X=function(c){if(!e.disabled){c=t.oc(c);var d=e.D[c.type];if(d)for(var d=d.slice(0),j=0,n=d.length;j<n&&!c.vc();j++)d[j].call(a,c)}});1==e.D[c].length&&(a.addEventListener?a.addEventListener(c,e.X,l):a.attachEvent&&a.attachEvent("on"+c,e.X))};
t.p=function(a,c,d){if(t.rc(a)){var e=t.getData(a);if(e.D){if(t.i.isArray(c))return u(t.p,a,c,d);if(c){var g=e.D[c];if(g){if(d){if(d.w)for(e=0;e<g.length;e++)g[e].w===d.w&&g.splice(e--,1)}else e.D[c]=[];t.ic(a,c)}}else for(g in e.D)c=g,e.D[c]=[],t.ic(a,c)}}};t.ic=function(a,c){var d=t.getData(a);0===d.D[c].length&&(delete d.D[c],a.removeEventListener?a.removeEventListener(c,d.X,l):a.detachEvent&&a.detachEvent("on"+c,d.X));t.Fb(d.D)&&(delete d.D,delete d.X,delete d.disabled);t.Fb(d)&&t.Dc(a)};
t.oc=function(a){function c(){return f}function d(){return l}if(!a||!a.Gb){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&("layerY"!==g&&"keyboardEvent.keyLocation"!==g)&&("returnValue"==g&&e.preventDefault||(a[g]=e[g]));a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.vd=c;a.defaultPrevented=f};a.vd=d;a.defaultPrevented=l;a.stopPropagation=function(){e.stopPropagation&&
e.stopPropagation();a.cancelBubble=f;a.Gb=c};a.Gb=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&e.stopImmediatePropagation();a.vc=c;a.stopPropagation()};a.vc=d;if(a.clientX!=k){g=document.documentElement;var h=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=k&&(a.button=a.button&1?0:a.button&
4?1:a.button&2?2:0)}return a};t.l=function(a,c){var d=t.rc(a)?t.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=t.oc(c);d.X&&d.X.call(a,c);if(e&&!c.Gb()&&c.bubbles!==l)t.l(e,c);else if(!e&&!c.defaultPrevented&&(d=t.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.defaultPrevented};
t.U=function(a,c,d){function e(){t.p(a,c,e);d.apply(this,arguments)}if(t.i.isArray(c))return u(t.U,a,c,d);e.w=d.w=d.w||t.w++;t.d(a,c,e)};function u(a,c,d,e){t.gc.forEach(d,function(d){a(c,d,e)})}var w=Object.prototype.hasOwnProperty;t.e=function(a,c){var d,e;d=document.createElement(a||"div");for(e in c)w.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};t.$=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};t.i={};
t.i.create=Object.create||function(a){function c(){}c.prototype=a;return new c};t.i.ia=function(a,c,d){for(var e in a)w.call(a,e)&&c.call(d||this,e,a[e])};t.i.B=function(a,c){if(!c)return a;for(var d in c)w.call(c,d)&&(a[d]=c[d]);return a};t.i.jd=function(a,c){var d,e,g;a=t.i.copy(a);for(d in c)w.call(c,d)&&(e=a[d],g=c[d],a[d]=t.i.Ta(e)&&t.i.Ta(g)?t.i.jd(e,g):c[d]);return a};t.i.copy=function(a){return t.i.B({},a)};
t.i.Ta=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};t.i.isArray=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};t.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.w||(c.w=t.w++);e.w=d?d+"_"+c.w:c.w;return e};t.ua={};t.w=1;t.expando="vdata"+(new Date).getTime();t.getData=function(a){var c=a[t.expando];c||(c=a[t.expando]=t.w++,t.ua[c]={});return t.ua[c]};
t.rc=function(a){a=a[t.expando];return!(!a||t.Fb(t.ua[a]))};t.Dc=function(a){var c=a[t.expando];if(c){delete t.ua[c];try{delete a[t.expando]}catch(d){a.removeAttribute?a.removeAttribute(t.expando):a[t.expando]=k}}};t.Fb=function(a){for(var c in a)if(a[c]!==k)return l;return f};t.n=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
t.r=function(a,c){var d,e;if(-1!=a.className.indexOf(c)){d=a.className.split(" ");for(e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};t.z=t.e("video");t.L=navigator.userAgent;t.Wc=/iPhone/i.test(t.L);t.Vc=/iPad/i.test(t.L);t.Xc=/iPod/i.test(t.L);t.Uc=t.Wc||t.Vc||t.Xc;var aa=t,x;var y=t.L.match(/OS (\d+)_/i);x=y&&y[1]?y[1]:b;aa.ge=x;t.Sc=/Android/i.test(t.L);var ba=t,z;var A=t.L.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),B,C;
A?(B=A[1]&&parseFloat(A[1]),C=A[2]&&parseFloat(A[2]),z=B&&C?parseFloat(A[1]+"."+A[2]):B?B:k):z=k;ba.Sb=z;t.Yc=t.Sc&&/webkit/i.test(t.L)&&2.3>t.Sb;t.Tc=/Firefox/i.test(t.L);t.he=/Chrome/i.test(t.L);t.cc=!!("ontouchstart"in window||window.Rc&&document instanceof window.Rc);
t.Sa=function(a){var c,d,e,g;c={};if(a&&a.attributes&&0<a.attributes.length){d=a.attributes;for(var h=d.length-1;0<=h;h--){e=d[h].name;g=d[h].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==k?f:l;c[e]=g}}return c};
t.je=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};t.Eb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};t.Oa={};t.v=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
t.ya=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),h=Math.floor(c/60%60),j=Math.floor(c/3600);if(isNaN(a)||Infinity===a)g=e=d="-";g=0<g||0<j?g+":":"";return g+(((g||10<=h)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};t.dd=function(){document.body.focus();document.onselectstart=r(l)};t.be=function(){document.onselectstart=r(f)};t.trim=function(a){return(a+"").replace(/^\s+|\s+$/g,"")};t.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
t.xb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
t.get=function(a,c,d,e){var g,h,j,n;d=d||m();"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});h=new XMLHttpRequest;j=t.Od(a);n=window.location;j.protocol+j.host!==n.protocol+n.host&&window.XDomainRequest&&!("withCredentials"in
h)?(h=new window.XDomainRequest,h.onload=function(){c(h.responseText)},h.onerror=d,h.onprogress=m(),h.ontimeout=d):(g="file:"==j.protocol||"file:"==n.protocol,h.onreadystatechange=function(){4===h.readyState&&(200===h.status||g&&0===h.status?c(h.responseText):d(h.responseText))});try{h.open("GET",a,f),e&&(h.withCredentials=f)}catch(q){d(q);return}try{h.send()}catch(v){d(v)}};
t.Td=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?t.log("LocalStorage Full (VideoJS)",d):18==d.code?t.log("LocalStorage not allowed (VideoJS)",d):t.log("LocalStorage Error (VideoJS)",d)}};t.qc=function(a){a.match(/^https?:\/\//)||(a=t.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
t.Od=function(a){var c,d,e,g;g="protocol hostname port pathname search hash host".split(" ");d=t.e("a",{href:a});if(e=""===d.host&&"file:"!==d.protocol)c=t.e("div"),c.innerHTML='<a href="'+a+'"></a>',d=c.firstChild,c.setAttribute("style","display:none; position:absolute;"),document.body.appendChild(c);a={};for(var h=0;h<g.length;h++)a[g[h]]=d[g[h]];e&&document.body.removeChild(c);return a};function D(){}var E=window.console||{log:D,warn:D,error:D};
function F(a,c){var d=Array.prototype.slice.call(c);a?d.unshift(a.toUpperCase()+":"):a="log";t.log.history.push(d);d.unshift("VIDEOJS:");if(E[a].apply)E[a].apply(E,d);else E[a](d.join(" "))}t.log=function(){F(k,arguments)};t.log.history=[];t.log.error=function(){F("error",arguments)};t.log.warn=function(){F("warn",arguments)};
t.rd=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:t.round(c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0)),top:t.round(c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0))}};t.gc={};t.gc.forEach=function(a,c,d){if(t.i.isArray(a)&&c instanceof Function)for(var e=0,g=a.length;e<g;++e)c.call(d||t,a[e],e,a);return a};t.pa={};
t.pa.Kb=function(a,c){var d,e,g;a=t.i.copy(a);for(d in c)c.hasOwnProperty(d)&&(e=a[d],g=c[d],a[d]=t.i.Ta(e)&&t.i.Ta(g)?t.pa.Kb(e,g):c[d]);return a};
t.a=t.qa.extend({j:function(a,c,d){this.c=a;this.k=t.i.copy(this.k);c=this.options(c);this.T=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+t.w++);this.Bd=c.name||k;this.b=c.el||this.e();this.M=[];this.Pa={};this.Qa={};this.tc();this.I(d);if(c.Ec!==l){var e,g;e=t.bind(this.m(),this.m().reportUserActivity);this.d("touchstart",function(){e();clearInterval(g);g=setInterval(e,250)});a=function(){e();clearInterval(g)};this.d("touchmove",e);this.d("touchend",a);this.d("touchcancel",a)}}});s=t.a.prototype;
s.dispose=function(){this.l({type:"dispose",bubbles:l});if(this.M)for(var a=this.M.length-1;0<=a;a--)this.M[a].dispose&&this.M[a].dispose();this.Qa=this.Pa=this.M=k;this.p();this.b.parentNode&&this.b.parentNode.removeChild(this.b);t.Dc(this.b);this.b=k};s.c=f;s.m=p("c");s.options=function(a){return a===b?this.k:this.k=t.pa.Kb(this.k,a)};s.e=function(a,c){return t.e(a,c)};s.v=p("b");s.ha=function(){return this.u||this.b};s.id=p("T");s.name=p("Bd");s.children=p("M");s.td=function(a){return this.Pa[a]};
s.ja=function(a){return this.Qa[a]};s.Q=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||t.$(e),c.name=e,d=new window.videojs[d](this.c||this,c)):d=a;this.M.push(d);"function"===typeof d.id&&(this.Pa[d.id()]=d);(e=e||d.name&&d.name())&&(this.Qa[e]=d);"function"===typeof d.el&&d.el()&&this.ha().appendChild(d.el());return d};
s.removeChild=function(a){"string"===typeof a&&(a=this.ja(a));if(a&&this.M){for(var c=l,d=this.M.length-1;0<=d;d--)if(this.M[d]===a){c=f;this.M.splice(d,1);break}c&&(this.Pa[a.id]=k,this.Qa[a.name]=k,(c=a.v())&&c.parentNode===this.ha()&&this.ha().removeChild(a.v()))}};s.tc=function(){var a,c,d,e;a=this;if(c=this.options().children)if(t.i.isArray(c))for(var g=0;g<c.length;g++)d=c[g],"string"==typeof d?(e=d,d={}):e=d.name,a[e]=a.Q(e,d);else t.i.ia(c,function(c,d){d!==l&&(a[c]=a.Q(c,d))})};s.S=r("");
s.d=function(a,c){t.d(this.b,a,t.bind(this,c));return this};s.p=function(a,c){t.p(this.b,a,c);return this};s.U=function(a,c){t.U(this.b,a,t.bind(this,c));return this};s.l=function(a){t.l(this.b,a);return this};s.I=function(a){a&&(this.ka?a.call(this):(this.$a===b&&(this.$a=[]),this.$a.push(a)));return this};s.Fa=function(){this.ka=f;var a=this.$a;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.$a=[];this.l("ready")}};s.n=function(a){t.n(this.b,a);return this};
s.r=function(a){t.r(this.b,a);return this};s.show=function(){this.b.style.display="block";return this};s.W=function(){this.b.style.display="none";return this};function G(a){a.r("vjs-lock-showing")}s.disable=function(){this.W();this.show=m()};s.width=function(a,c){return H(this,"width",a,c)};s.height=function(a,c){return H(this,"height",a,c)};s.md=function(a,c){return this.width(a,f).height(c)};
function H(a,c,d,e){if(d!==b)return a.b.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.l("resize"),a;if(!a.b)return 0;d=a.b.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.b["offset"+t.$(c)],10)}
function I(a){var c,d,e,g,h,j,n,q;c=0;d=k;a.d("touchstart",function(a){1===a.touches.length&&(d=a.touches[0],c=(new Date).getTime(),g=f)});a.d("touchmove",function(a){1<a.touches.length?g=l:d&&(j=a.touches[0].pageX-d.pageX,n=a.touches[0].pageY-d.pageY,q=Math.sqrt(j*j+n*n),22<q&&(g=l))});h=function(){g=l};a.d("touchleave",h);a.d("touchcancel",h);a.d("touchend",function(a){d=k;g===f&&(e=(new Date).getTime()-c,250>e&&(a.preventDefault(),this.l("tap")))})}
t.s=t.a.extend({j:function(a,c){t.a.call(this,a,c);I(this);this.d("tap",this.q);this.d("click",this.q);this.d("focus",this.Wa);this.d("blur",this.Va)}});s=t.s.prototype;
s.e=function(a,c){var d;c=t.i.B({className:this.S(),role:"button","aria-live":"polite",tabIndex:0},c);d=t.a.prototype.e.call(this,a,c);c.innerHTML||(this.u=t.e("div",{className:"vjs-control-content"}),this.vb=t.e("span",{className:"vjs-control-text",innerHTML:this.ta||"Need Text"}),this.u.appendChild(this.vb),d.appendChild(this.u));return d};s.S=function(){return"vjs-control "+t.a.prototype.S.call(this)};s.q=m();s.Wa=function(){t.d(document,"keyup",t.bind(this,this.ca))};
s.ca=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.q()};s.Va=function(){t.p(document,"keyup",t.bind(this,this.ca))};
t.P=t.a.extend({j:function(a,c){t.a.call(this,a,c);this.cd=this.ja(this.k.barName);this.handle=this.ja(this.k.handleName);this.d("mousedown",this.Xa);this.d("touchstart",this.Xa);this.d("focus",this.Wa);this.d("blur",this.Va);this.d("click",this.q);this.c.d("controlsvisible",t.bind(this,this.update));a.d(this.zc,t.bind(this,this.update));this.R={};this.R.move=t.bind(this,this.Ya);this.R.end=t.bind(this,this.Lb)}});s=t.P.prototype;
s.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=t.i.B({role:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return t.a.prototype.e.call(this,a,c)};s.Xa=function(a){a.preventDefault();t.dd();t.d(document,"mousemove",this.R.move);t.d(document,"mouseup",this.R.end);t.d(document,"touchmove",this.R.move);t.d(document,"touchend",this.R.end);this.Ya(a)};s.Ya=m();
s.Lb=function(){t.be();t.p(document,"mousemove",this.R.move,l);t.p(document,"mouseup",this.R.end,l);t.p(document,"touchmove",this.R.move,l);t.p(document,"touchend",this.R.end,l);this.update()};s.update=function(){if(this.b){var a,c=this.Db(),d=this.handle,e=this.cd;isNaN(c)&&(c=0);a=c;if(d){a=this.b.offsetWidth;var g=d.v().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.v().style.left=t.round(100*c,2)+"%"}e&&(e.v().style.width=t.round(100*a,2)+"%")}};
function J(a,c){var d,e,g,h;d=a.b;e=t.rd(d);h=g=d.offsetWidth;d=a.handle;if(a.options().vertical)return h=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.v().offsetHeight,h+=d/2,g-=d),Math.max(0,Math.min(1,(h-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.v().offsetWidth,g+=d/2,h-=d);return Math.max(0,Math.min(1,(e-g)/h))}s.Wa=function(){t.d(document,"keyup",t.bind(this,this.ca))};
s.ca=function(a){if(37==a.which||40==a.which)a.preventDefault(),this.Hc();else if(38==a.which||39==a.which)a.preventDefault(),this.Ic()};s.Va=function(){t.p(document,"keyup",t.bind(this,this.ca))};s.q=function(a){a.stopImmediatePropagation();a.preventDefault()};t.Y=t.a.extend();t.Y.prototype.defaultValue=0;
t.Y.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=t.i.B({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return t.a.prototype.e.call(this,"div",c)};t.fa=t.a.extend();function ca(a,c){a.Q(c);c.d("click",t.bind(a,function(){G(this)}))}
t.fa.prototype.e=function(){var a=this.options().jc||"ul";this.u=t.e(a,{className:"vjs-menu-content"});a=t.a.prototype.e.call(this,"div",{append:this.u,className:"vjs-menu"});a.appendChild(this.u);t.d(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};t.H=t.s.extend({j:function(a,c){t.s.call(this,a,c);this.selected(c.selected)}});t.H.prototype.e=function(a,c){return t.s.prototype.e.call(this,"li",t.i.B({className:"vjs-menu-item",innerHTML:this.k.label},c))};
t.H.prototype.q=function(){this.selected(f)};t.H.prototype.selected=function(a){a?(this.n("vjs-selected"),this.b.setAttribute("aria-selected",f)):(this.r("vjs-selected"),this.b.setAttribute("aria-selected",l))};t.K=t.s.extend({j:function(a,c){t.s.call(this,a,c);this.za=this.wa();this.Q(this.za);this.N&&0===this.N.length&&this.W();this.d("keyup",this.ca);this.b.setAttribute("aria-haspopup",f);this.b.setAttribute("role","button")}});s=t.K.prototype;s.sa=l;
s.wa=function(){var a=new t.fa(this.c);this.options().title&&a.ha().appendChild(t.e("li",{className:"vjs-menu-title",innerHTML:t.$(this.options().title),$d:-1}));if(this.N=this.createItems())for(var c=0;c<this.N.length;c++)ca(a,this.N[c]);return a};s.va=m();s.S=function(){return this.className+" vjs-menu-button "+t.s.prototype.S.call(this)};s.Wa=m();s.Va=m();s.q=function(){this.U("mouseout",t.bind(this,function(){G(this.za);this.b.blur()}));this.sa?K(this):L(this)};
s.ca=function(a){a.preventDefault();32==a.which||13==a.which?this.sa?K(this):L(this):27==a.which&&this.sa&&K(this)};function L(a){a.sa=f;a.za.n("vjs-lock-showing");a.b.setAttribute("aria-pressed",f);a.N&&0<a.N.length&&a.N[0].v().focus()}function K(a){a.sa=l;G(a.za);a.b.setAttribute("aria-pressed",l)}t.F=function(a){"number"===typeof a?this.code=a:"string"===typeof a?this.message=a:"object"===typeof a&&t.i.B(this,a);this.message||(this.message=t.F.kd[this.code]||"")};t.F.prototype.code=0;
t.F.prototype.message="";t.F.prototype.status=k;t.F.Ra="MEDIA_ERR_CUSTOM MEDIA_ERR_ABORTED MEDIA_ERR_NETWORK MEDIA_ERR_DECODE MEDIA_ERR_SRC_NOT_SUPPORTED MEDIA_ERR_ENCRYPTED".split(" ");
t.F.kd={1:"You aborted the video playback",2:"A network error caused the video download to fail part-way.",3:"The video playback was aborted due to a corruption problem or because the video used features your browser did not support.",4:"The video could not be loaded, either because the server or network failed or because the format is not supported.",5:"The video is encrypted and we do not have the keys to decrypt it."};for(var M=0;M<t.F.Ra.length;M++)t.F[t.F.Ra[M]]=M,t.F.prototype[t.F.Ra[M]]=M;
var N,O,P,Q;
N=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")];
O=N[0];for(Q=0;Q<N.length;Q++)if(N[Q][1]in document){P=N[Q];break}if(P){t.Oa.Cb={};for(Q=0;Q<P.length;Q++)t.Oa.Cb[O[Q]]=P[Q]}
t.Player=t.a.extend({j:function(a,c,d){this.O=a;a.id=a.id||"vjs_video_"+t.w++;c=t.i.B(da(a),c);this.A={};this.Ac=c.poster;this.wb=c.controls;a.controls=l;c.Ec=l;t.a.call(this,this,c,d);this.controls()?this.n("vjs-controls-enabled"):this.n("vjs-controls-disabled");t.Aa[this.T]=this;c.plugins&&t.i.ia(c.plugins,function(a,c){this[a](c)},this);var e,g,h,j,n,q;e=t.bind(this,this.reportUserActivity);this.d("mousedown",function(){e();clearInterval(g);g=setInterval(e,250)});this.d("mousemove",function(a){if(a.screenX!=
n||a.screenY!=q)n=a.screenX,q=a.screenY,e()});this.d("mouseup",function(){e();clearInterval(g)});this.d("keydown",e);this.d("keyup",e);h=setInterval(t.bind(this,function(){this.oa&&(this.oa=l,this.userActive(f),clearTimeout(j),j=setTimeout(t.bind(this,function(){this.oa||this.userActive(l)}),2E3))}),250);this.d("dispose",function(){clearInterval(h);clearTimeout(j)})}});s=t.Player.prototype;s.k=t.options;
s.dispose=function(){this.l("dispose");this.p("dispose");t.Aa[this.T]=k;this.O&&this.O.player&&(this.O.player=k);this.b&&this.b.player&&(this.b.player=k);clearInterval(this.Za);this.Ca();this.h&&this.h.dispose();t.a.prototype.dispose.call(this)};function da(a){var c={sources:[],tracks:[]};t.i.B(c,t.Sa(a));if(a.hasChildNodes()){var d,e,g,h;a=a.childNodes;g=0;for(h=a.length;g<h;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(t.Sa(d)):"track"===e&&c.tracks.push(t.Sa(d))}return c}
s.e=function(){var a=this.b=t.a.prototype.e.call(this,"div"),c=this.O,d;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var e,g,h,j,n;e=c.childNodes;g=e.length;for(n=[];g--;)h=e[g],j=h.nodeName.toLowerCase(),"track"===j&&n.push(h);for(e=0;e<n.length;e++)c.removeChild(n[e])}d=t.Sa(c);t.i.ia(d,function(c){a.setAttribute(c,d[c])});c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.n("vjs-paused");this.width(this.k.width,f);this.height(this.k.height,f);
c.parentNode&&c.parentNode.insertBefore(a,c);t.Eb(c,a);this.b=a;this.d("loadstart",this.Gd);this.d("waiting",this.Md);this.d(["canplay","canplaythrough","playing","ended"],this.Ld);this.d("seeking",this.Jd);this.d("seeked",this.Id);this.d("ended",this.Cd);this.d("play",this.Nb);this.d("firstplay",this.Ed);this.d("pause",this.Mb);this.d("progress",this.Hd);this.d("durationchange",this.xc);this.d("fullscreenchange",this.Fd);return a};
function R(a,c,d){a.h&&(a.ka=l,a.Ib&&(a.Ib=l,clearInterval(a.Za)),a.Jb&&S(a),a.h.dispose(),a.h=l);"Html5"!==c&&a.O&&(t.g.zb(a.O),a.O=k);a.bb=c;a.ka=l;var e=t.i.B({source:d,parentEl:a.b},a.k[c.toLowerCase()]);d&&(a.lc=d.type,d.src==a.A.src&&0<a.A.currentTime&&(e.startTime=a.A.currentTime),a.A.src=d.src);a.h=new window.videojs[c](a,e);a.h.I(function(){this.c.Fa();if(!this.o.progressEvents){var a=this.c;a.Ib=f;a.Za=setInterval(t.bind(a,function(){var a=this.bufferedPercent();this.A.bufferedPercent!=
a&&this.l("progress");this.A.bufferedPercent=a;1==a&&clearInterval(this.Za)}),500);a.h&&a.h.U("progress",function(){this.o.progressEvents=f;var a=this.c;a.Ib=l;clearInterval(a.Za)})}this.o.timeupdateEvents||(a=this.c,a.Jb=f,a.d("play",a.Lc),a.d("pause",a.Ca),a.h&&a.h.U("timeupdate",function(){this.o.timeupdateEvents=f;S(this.c)}))})}function S(a){a.Jb=l;a.Ca();a.p("play",a.Lc);a.p("pause",a.Ca)}s.Lc=function(){this.kc&&this.Ca();this.kc=setInterval(t.bind(this,function(){this.l("timeupdate")}),250)};
s.Ca=function(){clearInterval(this.kc);this.l("timeupdate")};s.Gd=function(){this.error(k);this.paused()?(ea(this,l),this.U("play",function(){ea(this,f)})):this.l("firstplay")};s.sc=l;function ea(a,c){c!==b&&a.sc!==c&&((a.sc=c)?(a.n("vjs-has-started"),a.l("firstplay")):a.r("vjs-has-started"))}s.Nb=function(){this.r("vjs-paused");this.n("vjs-playing")};s.Md=function(){this.n("vjs-waiting")};s.Ld=function(){this.r("vjs-waiting")};s.Jd=function(){this.n("vjs-seeking")};s.Id=function(){this.r("vjs-seeking")};
s.Ed=function(){this.k.starttime&&this.currentTime(this.k.starttime);this.n("vjs-has-started")};s.Mb=function(){this.r("vjs-playing");this.n("vjs-paused")};s.Hd=function(){1==this.bufferedPercent()&&this.l("loadedalldata")};s.Cd=function(){this.k.loop&&(this.currentTime(0),this.play())};s.xc=function(){var a=T(this,"duration");a&&(0>a&&(a=Infinity),this.duration(a),Infinity===a?this.n("vjs-live"):this.r("vjs-live"))};s.Fd=function(){this.isFullscreen()?this.n("vjs-fullscreen"):this.r("vjs-fullscreen")};
function U(a,c,d){if(a.h&&!a.h.ka)a.h.I(function(){this[c](d)});else try{a.h[c](d)}catch(e){throw t.log(e),e;}}function T(a,c){if(a.h&&a.h.ka)try{return a.h[c]()}catch(d){throw a.h[c]===b?t.log("Video.js: "+c+" method not defined for "+a.bb+" playback technology.",d):"TypeError"==d.name?(t.log("Video.js: "+c+" unavailable on "+a.bb+" playback technology element.",d),a.h.ka=l):t.log(d),d;}}s.play=function(){U(this,"play");return this};s.pause=function(){U(this,"pause");return this};
s.paused=function(){return T(this,"paused")===l?l:f};s.currentTime=function(a){return a!==b?(U(this,"setCurrentTime",a),this.Jb&&this.l("timeupdate"),this):this.A.currentTime=T(this,"currentTime")||0};s.duration=function(a){if(a!==b)return this.A.duration=parseFloat(a),this;this.A.duration===b&&this.xc();return this.A.duration||0};s.Cc=function(){return this.duration()-this.currentTime()};s.buffered=function(){var a=T(this,"buffered");if(!a||!a.length)a=t.xb(0,0);return a};
s.bufferedPercent=function(){var a=this.duration(),c=this.buffered(),d=0,e,g;if(!a)return 0;for(var h=0;h<c.length;h++)e=c.start(h),g=c.end(h),g>a&&(g=a),d+=g-e;return d/a};s.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.A.volume=a,U(this,"setVolume",a),t.Td(a),this;a=parseFloat(T(this,"volume"));return isNaN(a)?1:a};s.muted=function(a){return a!==b?(U(this,"setMuted",a),this):T(this,"muted")||l};s.Da=function(){return T(this,"supportsFullScreen")||l};s.uc=l;
s.isFullscreen=function(a){return a!==b?(this.uc=!!a,this):this.uc};s.isFullScreen=function(a){t.log.warn('player.isFullScreen() has been deprecated, use player.isFullscreen() with a lowercase "s")');return this.isFullscreen(a)};
s.requestFullscreen=function(){var a=t.Oa.Cb;this.isFullscreen(f);a?(t.d(document,a.fullscreenchange,t.bind(this,function(c){this.isFullscreen(document[a.fullscreenElement]);this.isFullscreen()===l&&t.p(document,a.fullscreenchange,arguments.callee);this.l("fullscreenchange")})),this.b[a.requestFullscreen]()):this.h.Da()?U(this,"enterFullScreen"):(this.nc(),this.l("fullscreenchange"));return this};
s.exitFullscreen=function(){var a=t.Oa.Cb;this.isFullscreen(l);if(a)document[a.exitFullscreen]();else this.h.Da()?U(this,"exitFullScreen"):(this.Ab(),this.l("fullscreenchange"));return this};s.nc=function(){this.wd=f;this.nd=document.documentElement.style.overflow;t.d(document,"keydown",t.bind(this,this.pc));document.documentElement.style.overflow="hidden";t.n(document.body,"vjs-full-window");this.l("enterFullWindow")};
s.pc=function(a){27===a.keyCode&&(this.isFullscreen()===f?this.exitFullscreen():this.Ab())};s.Ab=function(){this.wd=l;t.p(document,"keydown",this.pc);document.documentElement.style.overflow=this.nd;t.r(document.body,"vjs-full-window");this.l("exitFullWindow")};
s.src=function(a){if(a===b)return T(this,"src");t.i.isArray(a)?fa(this,a):"string"===typeof a?this.src({src:a}):a instanceof Object&&(a.type&&!window.videojs[this.bb].canPlaySource(a)?fa(this,[a]):(this.A.src=a.src,this.lc=a.type||"",this.I(function(){U(this,"src",a.src);"auto"==this.k.preload&&this.load();this.k.autoplay&&this.play()})));return this};
function fa(a,c){var d;a:{d=0;for(var e=a.k.techOrder;d<e.length;d++){var g=t.$(e[d]),h=window.videojs[g];if(h){if(h.isSupported())for(var j=0,n=c;j<n.length;j++){var q=n[j];if(h.canPlaySource(q)){d={source:q,h:g};break a}}}else t.log.error('The "'+g+'" tech is undefined. Skipped browser support check for that tech.')}d=l}d?d.h===a.bb?a.src(d.source):R(a,d.h,d.source):(a.error({code:4,message:a.options().notSupportedMessage}),a.Fa())}s.load=function(){U(this,"load");return this};
s.currentSrc=function(){return T(this,"currentSrc")||this.A.src||""};s.hd=function(){return this.lc||""};s.Ba=function(a){return a!==b?(U(this,"setPreload",a),this.k.preload=a,this):T(this,"preload")};s.autoplay=function(a){return a!==b?(U(this,"setAutoplay",a),this.k.autoplay=a,this):T(this,"autoplay")};s.loop=function(a){return a!==b?(U(this,"setLoop",a),this.k.loop=a,this):T(this,"loop")};s.poster=function(a){if(a===b)return this.Ac;this.Ac=a;U(this,"setPoster",a);this.l("posterchange")};
s.controls=function(a){return a!==b?(a=!!a,this.wb!==a&&((this.wb=a)?(this.r("vjs-controls-disabled"),this.n("vjs-controls-enabled"),this.l("controlsenabled")):(this.r("vjs-controls-enabled"),this.n("vjs-controls-disabled"),this.l("controlsdisabled"))),this):this.wb};t.Player.prototype.Rb;s=t.Player.prototype;
s.usingNativeControls=function(a){return a!==b?(a=!!a,this.Rb!==a&&((this.Rb=a)?(this.n("vjs-using-native-controls"),this.l("usingnativecontrols")):(this.r("vjs-using-native-controls"),this.l("usingcustomcontrols"))),this):this.Rb};s.ba=k;s.error=function(a){if(a===b)return this.ba;if(a===k)return this.ba=a,this.r("vjs-error"),this;this.ba=a instanceof t.F?a:new t.F(a);this.l("error");this.n("vjs-error");t.log.error("(CODE:"+this.ba.code+" "+t.F.Ra[this.ba.code]+")",this.ba.message,this.ba);return this};
s.ended=function(){return T(this,"ended")};s.seeking=function(){return T(this,"seeking")};s.oa=f;s.reportUserActivity=function(){this.oa=f};s.Qb=f;s.userActive=function(a){return a!==b?(a=!!a,a!==this.Qb&&((this.Qb=a)?(this.oa=f,this.r("vjs-user-inactive"),this.n("vjs-user-active"),this.l("useractive")):(this.oa=l,this.h&&this.h.U("mousemove",function(a){a.stopPropagation();a.preventDefault()}),this.r("vjs-user-active"),this.n("vjs-user-inactive"),this.l("userinactive"))),this):this.Qb};
s.playbackRate=function(a){return a!==b?(U(this,"setPlaybackRate",a),this):this.h&&this.h.o&&this.h.o.playbackRate?T(this,"playbackRate"):1};t.Ia=t.a.extend();t.Ia.prototype.k={le:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},liveDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{},playbackRateMenuButton:{}}};t.Ia.prototype.e=function(){return t.e("div",{className:"vjs-control-bar"})};
t.Wb=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});t.Wb.prototype.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-live-controls vjs-control"});this.u=t.e("div",{className:"vjs-live-display",innerHTML:'<span class="vjs-control-text">Stream Type </span>LIVE',"aria-live":"off"});a.appendChild(this.u);return a};t.Zb=t.s.extend({j:function(a,c){t.s.call(this,a,c);a.d("play",t.bind(this,this.Nb));a.d("pause",t.bind(this,this.Mb))}});s=t.Zb.prototype;s.ta="Play";
s.S=function(){return"vjs-play-control "+t.s.prototype.S.call(this)};s.q=function(){this.c.paused()?this.c.play():this.c.pause()};s.Nb=function(){t.r(this.b,"vjs-paused");t.n(this.b,"vjs-playing");this.b.children[0].children[0].innerHTML="Pause"};s.Mb=function(){t.r(this.b,"vjs-playing");t.n(this.b,"vjs-paused");this.b.children[0].children[0].innerHTML="Play"};t.fb=t.a.extend({j:function(a,c){t.a.call(this,a,c);a.d("timeupdate",t.bind(this,this.ea))}});
t.fb.prototype.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.u=t.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(this.u);return a};t.fb.prototype.ea=function(){var a=this.c.ab?this.c.A.currentTime:this.c.currentTime();this.u.innerHTML='<span class="vjs-control-text">Current Time </span>'+t.ya(a,this.c.duration())};
t.gb=t.a.extend({j:function(a,c){t.a.call(this,a,c);a.d("timeupdate",t.bind(this,this.ea))}});t.gb.prototype.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.u=t.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(this.u);return a};
t.gb.prototype.ea=function(){var a=this.c.duration();a&&(this.u.innerHTML='<span class="vjs-control-text">Duration Time </span>'+t.ya(a))};t.ec=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});t.ec.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};t.nb=t.a.extend({j:function(a,c){t.a.call(this,a,c);a.d("timeupdate",t.bind(this,this.ea))}});
t.nb.prototype.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.u=t.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(this.u);return a};t.nb.prototype.ea=function(){this.c.duration()&&(this.u.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+t.ya(this.c.Cc()))};
t.Ja=t.s.extend({j:function(a,c){t.s.call(this,a,c)}});t.Ja.prototype.ta="Fullscreen";t.Ja.prototype.S=function(){return"vjs-fullscreen-control "+t.s.prototype.S.call(this)};t.Ja.prototype.q=function(){this.c.isFullscreen()?(this.c.exitFullscreen(),this.vb.innerHTML="Fullscreen"):(this.c.requestFullscreen(),this.vb.innerHTML="Non-Fullscreen")};t.mb=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});t.mb.prototype.k={children:{seekBar:{}}};
t.mb.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};t.ac=t.P.extend({j:function(a,c){t.P.call(this,a,c);a.d("timeupdate",t.bind(this,this.na));a.I(t.bind(this,this.na))}});s=t.ac.prototype;s.k={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};s.zc="timeupdate";s.e=function(){return t.P.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
s.na=function(){var a=this.c.ab?this.c.A.currentTime:this.c.currentTime();this.b.setAttribute("aria-valuenow",t.round(100*this.Db(),2));this.b.setAttribute("aria-valuetext",t.ya(a,this.c.duration()))};s.Db=function(){return this.c.currentTime()/this.c.duration()};s.Xa=function(a){t.P.prototype.Xa.call(this,a);this.c.ab=f;this.de=!this.c.paused();this.c.pause()};s.Ya=function(a){a=J(this,a)*this.c.duration();a==this.c.duration()&&(a-=0.1);this.c.currentTime(a)};
s.Lb=function(a){t.P.prototype.Lb.call(this,a);this.c.ab=l;this.de&&this.c.play()};s.Ic=function(){this.c.currentTime(this.c.currentTime()+5)};s.Hc=function(){this.c.currentTime(this.c.currentTime()-5)};t.jb=t.a.extend({j:function(a,c){t.a.call(this,a,c);a.d("progress",t.bind(this,this.update))}});t.jb.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-load-progress"})};
t.jb.prototype.update=function(){var a,c,d,e,g=this.c.buffered();a=this.c.duration();var h,j=this.c;h=j.buffered();j=j.duration();h=h.end(h.length-1);h>j&&(h=j);j=this.b.children;this.b.style.width=100*(h/a||0)+"%";for(a=0;a<g.length;a++)c=g.start(a),d=g.end(a),(e=j[a])||(e=this.b.appendChild(t.e())),e.style.left=100*(c/h||0)+"%",e.style.width=100*((d-c)/h||0)+"%";for(a=j.length;a>g.length;a--)this.b.removeChild(j[a-1])};t.Yb=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});
t.Yb.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};t.La=t.Y.extend({j:function(a,c){t.Y.call(this,a,c);a.d("timeupdate",t.bind(this,this.ea))}});t.La.prototype.defaultValue="00:00";t.La.prototype.e=function(){return t.Y.prototype.e.call(this,"div",{className:"vjs-seek-handle","aria-live":"off"})};
t.La.prototype.ea=function(){var a=this.c.ab?this.c.A.currentTime:this.c.currentTime();this.b.innerHTML='<span class="vjs-control-text">'+t.ya(a,this.c.duration())+"</span>"};t.pb=t.a.extend({j:function(a,c){t.a.call(this,a,c);a.h&&(a.h.o&&a.h.o.volumeControl===l)&&this.n("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.h.o&&a.h.o.volumeControl===l?this.n("vjs-hidden"):this.r("vjs-hidden")}))}});t.pb.prototype.k={children:{volumeBar:{}}};
t.pb.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};t.ob=t.P.extend({j:function(a,c){t.P.call(this,a,c);a.d("volumechange",t.bind(this,this.na));a.I(t.bind(this,this.na))}});s=t.ob.prototype;s.na=function(){this.b.setAttribute("aria-valuenow",t.round(100*this.c.volume(),2));this.b.setAttribute("aria-valuetext",t.round(100*this.c.volume(),2)+"%")};s.k={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};
s.zc="volumechange";s.e=function(){return t.P.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};s.Ya=function(a){this.c.muted()&&this.c.muted(l);this.c.volume(J(this,a))};s.Db=function(){return this.c.muted()?0:this.c.volume()};s.Ic=function(){this.c.volume(this.c.volume()+0.1)};s.Hc=function(){this.c.volume(this.c.volume()-0.1)};t.fc=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});
t.fc.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};t.qb=t.Y.extend();t.qb.prototype.defaultValue="00:00";t.qb.prototype.e=function(){return t.Y.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
t.ga=t.s.extend({j:function(a,c){t.s.call(this,a,c);a.d("volumechange",t.bind(this,this.update));a.h&&(a.h.o&&a.h.o.volumeControl===l)&&this.n("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.h.o&&a.h.o.volumeControl===l?this.n("vjs-hidden"):this.r("vjs-hidden")}))}});t.ga.prototype.e=function(){return t.s.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};
t.ga.prototype.q=function(){this.c.muted(this.c.muted()?l:f)};t.ga.prototype.update=function(){var a=this.c.volume(),c=3;0===a||this.c.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.c.muted()?"Unmute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)t.r(this.b,"vjs-vol-"+a);t.n(this.b,"vjs-vol-"+c)};
t.ra=t.K.extend({j:function(a,c){t.K.call(this,a,c);a.d("volumechange",t.bind(this,this.update));a.h&&(a.h.o&&a.h.o.Oc===l)&&this.n("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.h.o&&a.h.o.Oc===l?this.n("vjs-hidden"):this.r("vjs-hidden")}));this.n("vjs-menu-button")}});t.ra.prototype.wa=function(){var a=new t.fa(this.c,{jc:"div"}),c=new t.ob(this.c,t.i.B({vertical:f},this.k.se));a.Q(c);return a};t.ra.prototype.q=function(){t.ga.prototype.q.call(this);t.K.prototype.q.call(this)};
t.ra.prototype.e=function(){return t.s.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};t.ra.prototype.update=t.ga.prototype.update;t.$b=t.K.extend({j:function(a,c){t.K.call(this,a,c);this.Nc();this.Mc();a.d("loadstart",t.bind(this,this.Nc));a.d("ratechange",t.bind(this,this.Mc))}});s=t.$b.prototype;
s.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-playback-rate vjs-menu-button vjs-control",innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">Playback Rate</span></div>'});this.wc=t.e("div",{className:"vjs-playback-rate-value",innerHTML:1});a.appendChild(this.wc);return a};s.wa=function(){var a=new t.fa(this.m()),c=this.m().options().playbackRates;if(c)for(var d=c.length-1;0<=d;d--)a.Q(new t.lb(this.m(),{rate:c[d]+"x"}));return a};
s.na=function(){this.v().setAttribute("aria-valuenow",this.m().playbackRate())};s.q=function(){for(var a=this.m().playbackRate(),c=this.m().options().playbackRates,d=c[0],e=0;e<c.length;e++)if(c[e]>a){d=c[e];break}this.m().playbackRate(d)};function ga(a){return a.m().h&&a.m().h.o.playbackRate&&a.m().options().playbackRates&&0<a.m().options().playbackRates.length}s.Nc=function(){ga(this)?this.r("vjs-hidden"):this.n("vjs-hidden")};
s.Mc=function(){ga(this)&&(this.wc.innerHTML=this.m().playbackRate()+"x")};t.lb=t.H.extend({jc:"button",j:function(a,c){var d=this.label=c.rate,e=this.Bc=parseFloat(d,10);c.label=d;c.selected=1===e;t.H.call(this,a,c);this.m().d("ratechange",t.bind(this,this.update))}});t.lb.prototype.q=function(){t.H.prototype.q.call(this);this.m().playbackRate(this.Bc)};t.lb.prototype.update=function(){this.selected(this.m().playbackRate()==this.Bc)};
t.Ka=t.s.extend({j:function(a,c){t.s.call(this,a,c);a.poster()&&this.src(a.poster());(!a.poster()||!a.controls())&&this.W();a.d("posterchange",t.bind(this,function(){this.src(a.poster())}));a.d("play",t.bind(this,this.W))}});var ha="backgroundSize"in t.z.style;t.Ka.prototype.e=function(){var a=t.e("div",{className:"vjs-poster",tabIndex:-1});ha||a.appendChild(t.e("img"));return a};t.Ka.prototype.src=function(a){var c=this.v();a!==b&&(ha?c.style.backgroundImage='url("'+a+'")':c.firstChild.src=a)};
t.Ka.prototype.q=function(){this.m().controls()&&this.c.play()};t.Xb=t.a.extend({j:function(a,c){t.a.call(this,a,c)}});t.Xb.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};t.cb=t.s.extend();t.cb.prototype.e=function(){return t.s.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:'<span aria-hidden="true"></span>',"aria-label":"play video"})};t.cb.prototype.q=function(){this.c.play()};
t.hb=t.a.extend({j:function(a,c){t.a.call(this,a,c);this.update();a.d("error",t.bind(this,this.update))}});t.hb.prototype.e=function(){var a=t.a.prototype.e.call(this,"div",{className:"vjs-error-display"});this.u=t.e("div");a.appendChild(this.u);return a};t.hb.prototype.update=function(){this.m().error()&&(this.u.innerHTML=this.m().error().message)};
t.t=t.a.extend({j:function(a,c,d){c=c||{};c.Ec=l;t.a.call(this,a,c,d);var e,g;g=this;e=this.m();a=function(){if(e.controls()&&!e.usingNativeControls()){var a;g.d("mousedown",g.q);g.d("touchstart",function(c){c.preventDefault();a=this.c.userActive()});g.d("touchmove",function(){a&&this.m().reportUserActivity()});I(g);g.d("tap",g.Kd)}};c=t.bind(g,g.Qd);this.I(a);e.d("controlsenabled",a);e.d("controlsdisabled",c);this.I(function(){this.networkState&&0<this.networkState()&&this.m().l("loadstart")})}});
s=t.t.prototype;s.Qd=function(){this.p("tap");this.p("touchstart");this.p("touchmove");this.p("touchleave");this.p("touchcancel");this.p("touchend");this.p("click");this.p("mousedown")};s.q=function(a){0===a.button&&this.m().controls()&&(this.m().paused()?this.m().play():this.m().pause())};s.Kd=function(){this.m().userActive(!this.m().userActive())};s.Fc=m();s.o={volumeControl:f,fullscreenResize:l,playbackRate:l,progressEvents:l,timeupdateEvents:l};t.media={};
t.g=t.t.extend({j:function(a,c,d){this.o.volumeControl=t.g.fd();this.o.playbackRate=t.g.ed();this.o.movingMediaElementInDOM=!t.Uc;this.o.fullscreenResize=f;t.t.call(this,a,c,d);for(d=t.g.ib.length-1;0<=d;d--)t.d(this.b,t.g.ib[d],t.bind(this,this.pd));if((c=c.source)&&this.b.currentSrc!==c.src)this.b.src=c.src;if(t.cc&&a.options().nativeControlsForTouch!==l){var e,g,h,j;e=this;g=this.m();c=g.controls();e.b.controls=!!c;h=function(){e.b.controls=f};j=function(){e.b.controls=l};g.d("controlsenabled",
h);g.d("controlsdisabled",j);c=function(){g.p("controlsenabled",h);g.p("controlsdisabled",j)};e.d("dispose",c);g.d("usingcustomcontrols",c);g.usingNativeControls(f)}a.I(function(){this.O&&(this.k.autoplay&&this.paused())&&(delete this.O.poster,this.play())});this.Fa()}});s=t.g.prototype;s.dispose=function(){t.g.zb(this.b);t.t.prototype.dispose.call(this)};
s.e=function(){var a=this.c,c=a.O,d;if(!c||this.o.movingMediaElementInDOM===l)c?(d=c.cloneNode(l),t.g.zb(c),c=d,a.O=k):c=t.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,t.Eb(c,a.v());d=["autoplay","preload","loop","muted"];for(var e=d.length-1;0<=e;e--){var g=d[e];a.k[g]!==k&&(c[g]=a.k[g])}return c};s.pd=function(a){"error"==a.type?this.m().error(this.error().code):(a.bubbles=l,this.m().l(a))};s.play=function(){this.b.play()};s.pause=function(){this.b.pause()};s.paused=function(){return this.b.paused};
s.currentTime=function(){return this.b.currentTime};s.Sd=function(a){try{this.b.currentTime=a}catch(c){t.log(c,"Video is not ready. (Video.js)")}};s.duration=function(){return this.b.duration||0};s.buffered=function(){return this.b.buffered};s.volume=function(){return this.b.volume};s.Yd=function(a){this.b.volume=a};s.muted=function(){return this.b.muted};s.Vd=function(a){this.b.muted=a};s.width=function(){return this.b.offsetWidth};s.height=function(){return this.b.offsetHeight};
s.Da=function(){return"function"==typeof this.b.webkitEnterFullScreen&&(/Android/.test(t.L)||!/Chrome|Mac OS X 10.5/.test(t.L))?f:l};s.mc=function(){var a=this.b;a.paused&&a.networkState<=a.fe?(this.b.play(),setTimeout(function(){a.pause();a.webkitEnterFullScreen()},0)):a.webkitEnterFullScreen()};s.qd=function(){this.b.webkitExitFullScreen()};s.src=function(a){this.b.src=a};s.load=function(){this.b.load()};s.currentSrc=function(){return this.b.currentSrc};s.poster=function(){return this.b.poster};
s.Fc=function(a){this.b.poster=a};s.Ba=function(){return this.b.Ba};s.Xd=function(a){this.b.Ba=a};s.autoplay=function(){return this.b.autoplay};s.Rd=function(a){this.b.autoplay=a};s.controls=function(){return this.b.controls};s.loop=function(){return this.b.loop};s.Ud=function(a){this.b.loop=a};s.error=function(){return this.b.error};s.seeking=function(){return this.b.seeking};s.ended=function(){return this.b.ended};s.playbackRate=function(){return this.b.playbackRate};
s.Wd=function(a){this.b.playbackRate=a};s.networkState=function(){return this.b.networkState};t.g.isSupported=function(){try{t.z.volume=0.5}catch(a){return l}return!!t.z.canPlayType};t.g.tb=function(a){try{return!!t.z.canPlayType(a.type)}catch(c){return""}};t.g.fd=function(){var a=t.z.volume;t.z.volume=a/2+0.1;return a!==t.z.volume};t.g.ed=function(){var a=t.z.playbackRate;t.z.playbackRate=a/2+0.1;return a!==t.z.playbackRate};var V,ia=/^application\/(?:x-|vnd\.apple\.)mpegurl/i,ja=/^video\/mp4/i;
t.g.yc=function(){4<=t.Sb&&(V||(V=t.z.constructor.prototype.canPlayType),t.z.constructor.prototype.canPlayType=function(a){return a&&ia.test(a)?"maybe":V.call(this,a)});t.Yc&&(V||(V=t.z.constructor.prototype.canPlayType),t.z.constructor.prototype.canPlayType=function(a){return a&&ja.test(a)?"maybe":V.call(this,a)})};t.g.ce=function(){var a=t.z.constructor.prototype.canPlayType;t.z.constructor.prototype.canPlayType=V;V=k;return a};t.g.yc();t.g.ib="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
t.g.zb=function(a){if(a){a.player=k;for(a.parentNode&&a.parentNode.removeChild(a);a.hasChildNodes();)a.removeChild(a.firstChild);a.removeAttribute("src");if("function"===typeof a.load)try{a.load()}catch(c){}}};
t.f=t.t.extend({j:function(a,c,d){t.t.call(this,a,c,d);var e=c.source;d=c.parentEl;var g=this.b=t.e("div",{id:a.id()+"_temp_flash"}),h=a.id()+"_flash_api",j=a.k,j=t.i.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:j.autoplay,preload:j.Ba,loop:j.loop,muted:j.muted},c.flashVars),n=t.i.B({wmode:"opaque",bgcolor:"#000000"},c.params),h=t.i.B({id:h,name:h,"class":"vjs-tech"},c.attributes);e&&(e.type&&t.f.yd(e.type)?
(e=t.f.Jc(e.src),j.rtmpConnection=encodeURIComponent(e.ub),j.rtmpStream=encodeURIComponent(e.Pb)):j.src=encodeURIComponent(t.qc(e.src)));t.Eb(g,d);c.startTime&&this.I(function(){this.load();this.play();this.currentTime(c.startTime)});t.Tc&&this.I(function(){t.d(this.v(),"mousemove",t.bind(this,function(){this.m().l({type:"mousemove",bubbles:l})}))});a.d("stageclick",a.reportUserActivity);this.b=t.f.od(c.swf,g,j,n,h)}});t.f.prototype.dispose=function(){t.t.prototype.dispose.call(this)};
t.f.prototype.play=function(){this.b.vjs_play()};t.f.prototype.pause=function(){this.b.vjs_pause()};t.f.prototype.src=function(a){if(a===b)return this.currentSrc();t.f.xd(a)?(a=t.f.Jc(a),this.ne(a.ub),this.oe(a.Pb)):(a=t.qc(a),this.b.vjs_src(a));if(this.c.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.f.prototype.setCurrentTime=function(a){this.Ad=a;this.b.vjs_setProperty("currentTime",a)};t.f.prototype.currentTime=function(){return this.seeking()?this.Ad||0:this.b.vjs_getProperty("currentTime")};
t.f.prototype.currentSrc=function(){var a=this.b.vjs_getProperty("currentSrc");if(a==k){var c=this.rtmpConnection(),d=this.rtmpStream();c&&d&&(a=t.f.Zd(c,d))}return a};t.f.prototype.load=function(){this.b.vjs_load()};t.f.prototype.poster=function(){this.b.vjs_getProperty("poster")};t.f.prototype.setPoster=m();t.f.prototype.buffered=function(){return t.xb(0,this.b.vjs_getProperty("buffered"))};t.f.prototype.Da=r(l);t.f.prototype.mc=r(l);
var ka=t.f.prototype,W="rtmpConnection rtmpStream preload defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),la="error networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function ma(){var a=W[X],c=a.charAt(0).toUpperCase()+a.slice(1);ka["set"+c]=function(c){return this.b.vjs_setProperty(a,c)}}
function na(a){ka[a]=function(){return this.b.vjs_getProperty(a)}}var X;for(X=0;X<W.length;X++)na(W[X]),ma();for(X=0;X<la.length;X++)na(la[X]);t.f.isSupported=function(){return 10<=t.f.version()[0]};t.f.tb=function(a){if(!a.type)return"";a=a.type.replace(/;.*/,"").toLowerCase();if(a in t.f.sd||a in t.f.Kc)return"maybe"};t.f.sd={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};t.f.Kc={"rtmp/mp4":"MP4","rtmp/flv":"FLV"};
t.f.onReady=function(a){var c;if(c=(a=t.v(a))&&a.parentNode&&a.parentNode.player)a.player=c,t.f.checkReady(c.h)};t.f.checkReady=function(a){a.v()&&(a.v().vjs_getProperty?a.Fa():setTimeout(function(){t.f.checkReady(a)},50))};t.f.onEvent=function(a,c){t.v(a).player.l(c)};t.f.onError=function(a,c){var d=t.v(a).player,e="FLASH: "+c;"srcnotfound"==c?d.error({code:4,message:e}):d.error(e)};
t.f.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
t.f.od=function(a,c,d,e,g){a=t.f.ud(a,d,e,g);a=t.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var h=d.childNodes[0];setTimeout(function(){h.style.display="block"},1E3);return a};
t.f.ud=function(a,c,d,e){var g="",h="",j="";c&&t.i.ia(c,function(a,c){g+=a+"="+c+"&amp;"});d=t.i.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);t.i.ia(d,function(a,c){h+='<param name="'+a+'" value="'+c+'" />'});e=t.i.B({data:a,width:"100%",height:"100%"},e);t.i.ia(e,function(a,c){j+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+j+">"+h+"</object>"};t.f.Zd=function(a,c){return a+"&"+c};
t.f.Jc=function(a){var c={ub:"",Pb:""};if(!a)return c;var d=a.indexOf("&"),e;-1!==d?e=d+1:(d=e=a.lastIndexOf("/")+1,0===d&&(d=e=a.length));c.ub=a.substring(0,d);c.Pb=a.substring(e,a.length);return c};t.f.yd=function(a){return a in t.f.Kc};t.f.$c=/^rtmp[set]?:\/\//i;t.f.xd=function(a){return t.f.$c.test(a)};
t.Zc=t.a.extend({j:function(a,c,d){t.a.call(this,a,c,d);if(!a.k.sources||0===a.k.sources.length){c=0;for(d=a.k.techOrder;c<d.length;c++){var e=t.$(d[c]),g=window.videojs[e];if(g&&g.isSupported()){R(a,e);break}}}else a.src(a.k.sources)}});t.Player.prototype.textTracks=function(){return this.Ea=this.Ea||[]};
function oa(a,c,d,e,g){var h=a.Ea=a.Ea||[];g=g||{};g.kind=c;g.label=d;g.language=e;c=t.$(c||"subtitles");var j=new window.videojs[c+"Track"](a,g);h.push(j);j.yb()&&a.I(function(){setTimeout(function(){Y(j.m(),j.id())},0)})}function Y(a,c,d){for(var e=a.Ea,g=0,h=e.length,j,n;g<h;g++)j=e[g],j.id()===c?(j.show(),n=j):d&&(j.J()==d&&0<j.mode())&&j.disable();(c=n?n.J():d?d:l)&&a.l(c+"trackchange")}
t.C=t.a.extend({j:function(a,c){t.a.call(this,a,c);this.T=c.id||"vjs_"+c.kind+"_"+c.language+"_"+t.w++;this.Gc=c.src;this.ld=c["default"]||c.dflt;this.ae=c.title;this.ke=c.srclang;this.zd=c.label;this.aa=[];this.rb=[];this.la=this.ma=0;this.c.d("fullscreenchange",t.bind(this,this.bd))}});s=t.C.prototype;s.J=p("G");s.src=p("Gc");s.yb=p("ld");s.title=p("ae");s.label=p("zd");s.gd=p("aa");s.ad=p("rb");s.readyState=p("ma");s.mode=p("la");
s.bd=function(){this.b.style.fontSize=this.c.isFullScreen()?140*(screen.width/this.c.width())+"%":""};s.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-"+this.G+" vjs-text-track"})};s.show=function(){pa(this);this.la=2;t.a.prototype.show.call(this)};s.W=function(){pa(this);this.la=1;t.a.prototype.W.call(this)};
s.disable=function(){2==this.la&&this.W();this.c.p("timeupdate",t.bind(this,this.update,this.T));this.c.p("ended",t.bind(this,this.reset,this.T));this.reset();this.c.ja("textTrackDisplay").removeChild(this);this.la=0};function pa(a){0===a.ma&&a.load();0===a.la&&(a.c.d("timeupdate",t.bind(a,a.update,a.T)),a.c.d("ended",t.bind(a,a.reset,a.T)),("captions"===a.G||"subtitles"===a.G)&&a.c.ja("textTrackDisplay").Q(a))}
s.load=function(){0===this.ma&&(this.ma=1,t.get(this.Gc,t.bind(this,this.Nd),t.bind(this,this.Dd)))};s.Dd=function(a){this.error=a;this.ma=3;this.l("error")};s.Nd=function(a){var c,d;a=a.split("\n");for(var e="",g=1,h=a.length;g<h;g++)if(e=t.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=t.trim(a[++g])):c=this.aa.length;c={id:c,index:this.aa.length};d=e.split(/[\t ]+/);c.startTime=qa(d[0]);c.xa=qa(d[2]);for(d=[];a[++g]&&(e=t.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.aa.push(c)}this.ma=2;this.l("loaded")};
function qa(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
s.update=function(){if(0<this.aa.length){var a=this.c.options().trackTimeOffset||0,a=this.c.currentTime()+a;if(this.Ob===b||a<this.Ob||this.Ua<=a){var c=this.aa,d=this.c.duration(),e=0,g=l,h=[],j,n,q,v;a>=this.Ua||this.Ua===b?v=this.Bb!==b?this.Bb:0:(g=f,v=this.Hb!==b?this.Hb:c.length-1);for(;;){q=c[v];if(q.xa<=a)e=Math.max(e,q.xa),q.Na&&(q.Na=l);else if(a<q.startTime){if(d=Math.min(d,q.startTime),q.Na&&(q.Na=l),!g)break}else g?(h.splice(0,0,q),n===b&&(n=v),j=v):(h.push(q),j===b&&(j=v),n=v),d=Math.min(d,
q.xa),e=Math.max(e,q.startTime),q.Na=f;if(g)if(0===v)break;else v--;else if(v===c.length-1)break;else v++}this.rb=h;this.Ua=d;this.Ob=e;this.Bb=j;this.Hb=n;j=this.rb;n="";a=0;for(c=j.length;a<c;a++)n+='<span class="vjs-tt-cue">'+j[a].text+"</span>";this.b.innerHTML=n;this.l("cuechange")}}};s.reset=function(){this.Ua=0;this.Ob=this.c.duration();this.Hb=this.Bb=0};t.Ub=t.C.extend();t.Ub.prototype.G="captions";t.bc=t.C.extend();t.bc.prototype.G="subtitles";t.Vb=t.C.extend();t.Vb.prototype.G="chapters";
t.dc=t.a.extend({j:function(a,c,d){t.a.call(this,a,c,d);if(a.k.tracks&&0<a.k.tracks.length){c=this.c;a=a.k.tracks;for(var e=0;e<a.length;e++)d=a[e],oa(c,d.kind,d.label,d.language,d)}}});t.dc.prototype.e=function(){return t.a.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};t.Z=t.H.extend({j:function(a,c){var d=this.da=c.track;c.label=d.label();c.selected=d.yb();t.H.call(this,a,c);this.c.d(d.J()+"trackchange",t.bind(this,this.update))}});
t.Z.prototype.q=function(){t.H.prototype.q.call(this);Y(this.c,this.da.T,this.da.J())};t.Z.prototype.update=function(){this.selected(2==this.da.mode())};t.kb=t.Z.extend({j:function(a,c){c.track={J:function(){return c.kind},m:a,label:function(){return c.kind+" off"},yb:r(l),mode:r(l)};t.Z.call(this,a,c);this.selected(f)}});t.kb.prototype.q=function(){t.Z.prototype.q.call(this);Y(this.c,this.da.T,this.da.J())};
t.kb.prototype.update=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.J()==this.da.J()&&2==e.mode()&&(g=l);this.selected(g)};t.V=t.K.extend({j:function(a,c){t.K.call(this,a,c);1>=this.N.length&&this.W()}});t.V.prototype.va=function(){var a=[],c;a.push(new t.kb(this.c,{kind:this.G}));for(var d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.J()===this.G&&a.push(new t.Z(this.c,{track:c}));return a};
t.Ga=t.V.extend({j:function(a,c,d){t.V.call(this,a,c,d);this.b.setAttribute("aria-label","Captions Menu")}});t.Ga.prototype.G="captions";t.Ga.prototype.ta="Captions";t.Ga.prototype.className="vjs-captions-button";t.Ma=t.V.extend({j:function(a,c,d){t.V.call(this,a,c,d);this.b.setAttribute("aria-label","Subtitles Menu")}});t.Ma.prototype.G="subtitles";t.Ma.prototype.ta="Subtitles";t.Ma.prototype.className="vjs-subtitles-button";
t.Ha=t.V.extend({j:function(a,c,d){t.V.call(this,a,c,d);this.b.setAttribute("aria-label","Chapters Menu")}});s=t.Ha.prototype;s.G="chapters";s.ta="Chapters";s.className="vjs-chapters-button";s.va=function(){for(var a=[],c,d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.J()===this.G&&a.push(new t.Z(this.c,{track:c}));return a};
s.wa=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g,h=this.N=[];c<d;c++)if(e=a[c],e.J()==this.G)if(0===e.readyState())e.load(),e.d("loaded",t.bind(this,this.wa));else{g=e;break}a=this.za;a===b&&(a=new t.fa(this.c),a.ha().appendChild(t.e("li",{className:"vjs-menu-title",innerHTML:t.$(this.G),$d:-1})));if(g){e=g.aa;for(var j,c=0,d=e.length;c<d;c++)j=e[c],j=new t.eb(this.c,{track:g,cue:j}),h.push(j),a.Q(j);this.Q(a)}0<this.N.length&&this.show();return a};
t.eb=t.H.extend({j:function(a,c){var d=this.da=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.xa;t.H.call(this,a,c);d.d("cuechange",t.bind(this,this.update))}});t.eb.prototype.q=function(){t.H.prototype.q.call(this);this.c.currentTime(this.cue.startTime);this.update(this.cue.startTime)};t.eb.prototype.update=function(){var a=this.cue,c=this.c.currentTime();this.selected(a.startTime<=c&&c<a.xa)};
t.i.B(t.Ia.prototype.k.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)t.JSON=window.JSON;else{t.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;t.JSON.parse=function(a,c){function d(a,e){var j,n,q=a[e];if(q&&"object"===typeof q)for(j in q)Object.prototype.hasOwnProperty.call(q,j)&&(n=d(q,j),n!==b?q[j]=n:delete q[j]);return c.call(a,e,q)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
t.hc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==k&&(a=t.JSON.parse(a||"{}"),videojs(c,a)));else{t.sb();break}else t.Pc||t.sb()};t.sb=function(){setTimeout(t.hc,1)};"complete"===document.readyState?t.Pc=f:t.U(window,"load",function(){t.Pc=f});t.sb();t.Pd=function(a,c){t.Player.prototype[a]=c};var ra=this;ra.ee=f;function $(a,c){var d=a.split("."),e=ra;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",t);$("_V_",t);$("videojs.options",t.options);$("videojs.players",t.Aa);$("videojs.TOUCH_ENABLED",t.cc);$("videojs.cache",t.ua);$("videojs.Component",t.a);t.a.prototype.player=t.a.prototype.m;t.a.prototype.options=t.a.prototype.options;t.a.prototype.init=t.a.prototype.j;t.a.prototype.dispose=t.a.prototype.dispose;t.a.prototype.createEl=t.a.prototype.e;t.a.prototype.contentEl=t.a.prototype.ha;t.a.prototype.el=t.a.prototype.v;t.a.prototype.addChild=t.a.prototype.Q;
t.a.prototype.getChild=t.a.prototype.ja;t.a.prototype.getChildById=t.a.prototype.td;t.a.prototype.children=t.a.prototype.children;t.a.prototype.initChildren=t.a.prototype.tc;t.a.prototype.removeChild=t.a.prototype.removeChild;t.a.prototype.on=t.a.prototype.d;t.a.prototype.off=t.a.prototype.p;t.a.prototype.one=t.a.prototype.U;t.a.prototype.trigger=t.a.prototype.l;t.a.prototype.triggerReady=t.a.prototype.Fa;t.a.prototype.show=t.a.prototype.show;t.a.prototype.hide=t.a.prototype.W;
t.a.prototype.width=t.a.prototype.width;t.a.prototype.height=t.a.prototype.height;t.a.prototype.dimensions=t.a.prototype.md;t.a.prototype.ready=t.a.prototype.I;t.a.prototype.addClass=t.a.prototype.n;t.a.prototype.removeClass=t.a.prototype.r;t.a.prototype.buildCSSClass=t.a.prototype.S;t.Player.prototype.ended=t.Player.prototype.ended;t.Player.prototype.enterFullWindow=t.Player.prototype.nc;t.Player.prototype.exitFullWindow=t.Player.prototype.Ab;t.Player.prototype.preload=t.Player.prototype.Ba;
t.Player.prototype.remainingTime=t.Player.prototype.Cc;t.Player.prototype.supportsFullScreen=t.Player.prototype.Da;t.Player.prototype.currentType=t.Player.prototype.hd;$("videojs.MediaLoader",t.Zc);$("videojs.TextTrackDisplay",t.dc);$("videojs.ControlBar",t.Ia);$("videojs.Button",t.s);$("videojs.PlayToggle",t.Zb);$("videojs.FullscreenToggle",t.Ja);$("videojs.BigPlayButton",t.cb);$("videojs.LoadingSpinner",t.Xb);$("videojs.CurrentTimeDisplay",t.fb);$("videojs.DurationDisplay",t.gb);
$("videojs.TimeDivider",t.ec);$("videojs.RemainingTimeDisplay",t.nb);$("videojs.LiveDisplay",t.Wb);$("videojs.ErrorDisplay",t.hb);$("videojs.Slider",t.P);$("videojs.ProgressControl",t.mb);$("videojs.SeekBar",t.ac);$("videojs.LoadProgressBar",t.jb);$("videojs.PlayProgressBar",t.Yb);$("videojs.SeekHandle",t.La);$("videojs.VolumeControl",t.pb);$("videojs.VolumeBar",t.ob);$("videojs.VolumeLevel",t.fc);$("videojs.VolumeMenuButton",t.ra);$("videojs.VolumeHandle",t.qb);$("videojs.MuteToggle",t.ga);
$("videojs.PosterImage",t.Ka);$("videojs.Menu",t.fa);$("videojs.MenuItem",t.H);$("videojs.MenuButton",t.K);$("videojs.PlaybackRateMenuButton",t.$b);t.K.prototype.createItems=t.K.prototype.va;t.V.prototype.createItems=t.V.prototype.va;t.Ha.prototype.createItems=t.Ha.prototype.va;$("videojs.SubtitlesButton",t.Ma);$("videojs.CaptionsButton",t.Ga);$("videojs.ChaptersButton",t.Ha);$("videojs.MediaTechController",t.t);t.t.prototype.features=t.t.prototype.o;t.t.prototype.o.volumeControl=t.t.prototype.o.Oc;
t.t.prototype.o.fullscreenResize=t.t.prototype.o.ie;t.t.prototype.o.progressEvents=t.t.prototype.o.me;t.t.prototype.o.timeupdateEvents=t.t.prototype.o.pe;t.t.prototype.setPoster=t.t.prototype.Fc;$("videojs.Html5",t.g);t.g.Events=t.g.ib;t.g.isSupported=t.g.isSupported;t.g.canPlaySource=t.g.tb;t.g.patchCanPlayType=t.g.yc;t.g.unpatchCanPlayType=t.g.ce;t.g.prototype.setCurrentTime=t.g.prototype.Sd;t.g.prototype.setVolume=t.g.prototype.Yd;t.g.prototype.setMuted=t.g.prototype.Vd;
t.g.prototype.setPreload=t.g.prototype.Xd;t.g.prototype.setAutoplay=t.g.prototype.Rd;t.g.prototype.setLoop=t.g.prototype.Ud;t.g.prototype.enterFullScreen=t.g.prototype.mc;t.g.prototype.exitFullScreen=t.g.prototype.qd;t.g.prototype.playbackRate=t.g.prototype.playbackRate;t.g.prototype.setPlaybackRate=t.g.prototype.Wd;$("videojs.Flash",t.f);t.f.isSupported=t.f.isSupported;t.f.canPlaySource=t.f.tb;t.f.onReady=t.f.onReady;$("videojs.TextTrack",t.C);t.C.prototype.label=t.C.prototype.label;
t.C.prototype.kind=t.C.prototype.J;t.C.prototype.mode=t.C.prototype.mode;t.C.prototype.cues=t.C.prototype.gd;t.C.prototype.activeCues=t.C.prototype.ad;$("videojs.CaptionsTrack",t.Ub);$("videojs.SubtitlesTrack",t.bc);$("videojs.ChaptersTrack",t.Vb);$("videojs.autoSetup",t.hc);$("videojs.plugin",t.Pd);$("videojs.createTimeRange",t.xb);$("videojs.util",t.pa);t.pa.mergeOptions=t.pa.Kb;})();
